Repository gaearon/overreacted.io, pull requests merged in 2019-03, with the labels that each got.

#309 Add Korean translations for 'react-as-a-ui-runtime' doc
  src/pages/react-as-a-ui-runtime/index.ko.md
  src/utils/global.css
Labels: In Review

#326 fix Spelling mistakes `Commonts` to `Comments`
  src/pages/react-as-a-ui-runtime/index.zh-hans.md
Labels: Type: Typo

#295 typo fix
  src/pages/making-setinterval-declarative-with-react-hooks/index.md
Labels: Type: Typo

#288 Fix typo "construtor"
  src/pages/why-do-we-write-super-props/index.pt-br.md
Labels: Type: Typo

#313 index.tr.md - Translated to Turkish - Optimized for Change
  src/pages/optimized-for-change/index.tr.md
Labels: In Review

#315 (pt-BR) Translate "Fix Like No One’s Watching" to Portuguese
  src/pages/fix-like-no-ones-watching/index.pt-br.md
Labels: Need Review

#322 index.tr.md - Translated to Turkish - fix-like-no-ones-watching
  src/pages/fix-like-no-ones-watching/index.tr.md
Labels: Need Review

#323 Fix typo in Korean translation
  src/pages/the-elements-of-ui-engineering/index.ko.md
Labels: Need Review, Type: Typo

#329 Typo fix in the Conditions section
  src/pages/react-as-a-ui-runtime/index.md
Labels: Type: Typo

#330 Added "View all translated posts" for Russian translations
  src/templates/blog-post.js
Labels: Need Review

#331 Translate 'Fix Like No One’s Watching' to Polish
  src/pages/fix-like-no-ones-watching/index.pl.md
Labels: Need Review

#336 Arabic support and Optimized for Change post translation
  i18n.js
  src/fonts/files/Cairo-Bold.ttf
  src/fonts/files/Cairo-Regular.ttf
  src/fonts/fonts-post.arabic.css
  src/pages/optimized-for-change/index.ar.md
  src/utils/global.css
  src/utils/i18n.js
Labels: Need Review

#341 Translate "Coping with feedback" into Japanese
  src/pages/coping-with-feedback/index.ja.md
Labels: Need Review

#345 Japanese translation of How Are Function Components Different from Cl…
  src/pages/how-are-function-components-different-from-classes/index.ja.md
Labels: Need Review

#347 Fix single typo in "Coping with Feedback"
  src/pages/coping-with-feedback/index.md
Labels: Type: Typo

#328 translate Preparing for a Tech Talk, Part 1: Motivation to Chinese
  src/pages/preparing-for-tech-talk-part-1-motivation/index.zh-hans.md
Labels: In Review

#304 translate <optimized for change> to chinese
  src/pages/making-setinterval-declarative-with-react-hooks/index.zh-hans.md
  src/pages/why-do-hooks-rely-on-call-order/index.zh-hans.md
  src/pages/why-do-react-elements-have-typeof-property/index.zh-hans.md
Labels: In Review, Need Revision

#358 Translate <How are function Components...> Into Korean
  src/pages/how-are-function-components-different-from-classes/index.ko.md
Labels: Need Review

#348 Translate to Portuguese: How Are Function Components Different from…
  src/pages/how-are-function-components-different-from-classes/index.pt-br.md
Labels: Need Review

#365 Indonesian translation to coping-with-feedback
  src/pages/coping-with-feedback/index.id.md
Labels: Need Review

#368 Translate coping-with-feedback into Italian
  src/pages/coping-with-feedback/index.it.md
Labels: Need Review
